name: squaremap
version: $version
main: xyz.jpenilla.squaremap.paper.SquaremapPaperBootstrap
load: STARTUP
description: $description
authors:
 - jmp
website: $website
api-version: $apiVersion
folia-supported: true
